"""empty message

Revision ID: c5d8dd2855cf
Revises: 67720836cc61
Create Date: 2022-04-04 16:27:17.600861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d8dd2855cf'
down_revision = '67720836cc61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('level_prize', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('levels', 'level_prize')
    # ### end Alembic commands ###
